### ISSUE TITLE
Memory issue for longer tests

### ISSUE THREAD

**Issue by markgandy** [shoreditch-ops/artillery#130]
We are seeing an issue with artillery running out of memory for longer tests - memory gradually increases until it hits limit, then CPU spikes and the test crashes. I don't know if there is a memory leak somewhere - we are running tests up to around 30 requests per second. Artillery is running in a docker container (with 1GB of memory allocated) on a t2.small in AWS.

Config has multiple phases:

```
  phases:
    - duration: 300
      arrivalRate: 10
    - duration: 300
      arrivalRate: 12
    - duration: 300
      arrivalRate: 14
    - duration: 300
      arrivalRate: 16
    - duration: 300
      arrivalRate: 18
    - duration: 300
      arrivalRate: 20
    - duration: 300
      arrivalRate: 22
    - duration: 300
      arrivalRate: 24
    - duration: 300
      arrivalRate: 26
    - duration: 300
      arrivalRate: 28
    - duration: 300
      arrivalRate: 30
```

with each scenario just calling a single GET request
