### ISSUE TITLE
[Question] How to monitor messages arriving on socket.io channel?

### ISSUE THREAD

**Issue by gboysko** [shoreditch-ops/artillery#170]
I understand how flows can be written to emit socket.io messages and wait (for some indeterminate amount of time) for a response message, but how would we write flows that can receive arbitrary (real-time) messages sent from other virtual users? 

I can envision some type of `monitor` function that receives messages for a given flow and can verify that they are correct. Perhaps this monitoring can occur during a "think" phase.

I don't see anything in the documentation that addresses this type of real-time message validation. Is that consistent with the vision for Artillery?

**Comment by hassy** [comment]
You're right @gboysko, there's nothing like it in Artillery yet, but it's definitely something worth adding! What is your exact use case?

**Comment by gboysko** [comment]
Yeah, that's pretty close to what I'm thinking. My use case is what you'd expect in many chat/collaboration services: new messages arrive as users interact and I'd like to ensure that the messages received are consistent with the scenario/flow. I'd love to be able to "fail" the flow if an unexpected message was received (or an expected message contained fields indicating a failure condition).

I'm not sure how we would indicate that a flow remains in a "listening" state (other than re-purposing `think`).

**Comment by hassy** [comment]
Cool, this is definitely a needed feature (not just for Socket.io either, but also for WebSockets and any other async protocol we want to support like MQTT or XMPP).

As the first experiment we could go ahead with something like this:

1. Support defining an `onMessage` function that would be invoked for every incoming message, which you could use to implement a custom counter for example. This would be completely async.

```yaml
scenarios:
  - name: "A Socket.io scenario"
    onMessage: "myOnMessageHandler"
    flow:
      - emit: "something" # flow definition here
```

2. Add a `listen` command to flows. The function specified in a `listen` command will receive every incoming message from that point onwards until it gives control back to the flow.

```yaml
scenarios:
  - name: "A Socket.io scenario"
    flow:
      - emit: "something" # flow definition here
      - listen: "myHandlerFunction"
      - emit: "somethingElse"
```

I can give it a go some time in the next few weeks, but it's up for grabs if someone wants to give it a go and open a PR before then.
