### ISSUE TITLE
beforeRequest hook doesn't work

### ISSUE THREAD

**Issue by andrevas** [shoreditch-ops/artillery#184]
Hi guys!
I noticed the next issue:
When trying to change my json before sending, defined beforeRequest function is not called. Adding afterResponse function working as expected. My code looks like that: 

``` json
 {
  "config": {
    "target": "...my target...",
    "phases": [
      {"duration": 10, "arrivalRate": 5}
    ],
    "processor" : "helloJS.js",
    "defaults": {
      "headers": {
        "content-type": "application/json"
      }
    }
  },
  "scenarios": [
    {
      "flow": [
        {
          "post": {
            "url": "...my url...",
            "json": {
                 "my json"
            },
            "beforeRequest" : "foo"
          }
        }
      ]
    }
  ]
}
```

``` javascript
module.exports = {
    foo: foo
};

function foo (requestParams, context, ee, next) {
    console.log("TEST");
    return next();
}
```

**Comment by hassy** [comment]
Thanks @andrevas. Your code looks right and should be working, will need to investigate.

**Comment by danielo515** [comment]
It is happening for me too.

In my case it only happens if I do the following

```js
// file a.js
module.exports.funA = myfunction
```

```js
// file b.js
module.exports.funB = myfunction
```

```js
// file artillery.js
Object.assign( module.exports , require('./a.js'), require('./b.js'));
```

Then I configure those for the scenario:


```yml
config:
    target: 'https://localhost:3000'
    processor: "./artillery.js"
    tls:
        rejectUnauthorized: false
    phases:
        - duration: 10
          arrivalRate: 20
scenarios:
    - beforeRequest: ["funA","funB"]
      flow:
        - get:
            url: "/test"
            json: "{}"
```

If I import just one file it works
