### ISSUE TITLE
Add init hook or config file that runs before the scenarios

### ISSUE THREAD

**Issue by JohnieLee** [shoreditch-ops/artillery#197]
The use case that I have is that I have a config file of login/passwords and environment settings that I want to load into the context before the scenarios are run.  My current work around is to have a dummy request to an innocuous endpoint that uses a beforeRequest hook to init the context.

What I'd like to have is a parameter in the `config` block that either loads a config file into the context or an `init` hook that will call the processor to initialize the context from my config files.

**Comment by hassy** [comment]
@JohnieLee there's a way to run an arbitrary function using a `function` step, e.g.:

```yaml
scenarios:
  - name: "A scenario"
    flow:
      - function: "setupContext"
      - get:
        url: "/some/endpoint/{{ someId }}"
```

where `setupContext` is something like:

```javascript
function setupContext(context, ee, done) {
  context.vars.someId = 12345;
  return done();
}
```
