### ISSUE TITLE
"function" breaks when used inside a loop

### ISSUE THREAD

**Issue by steveschnepp** [shoreditch-ops/artillery#216]
```
        -
          count: 2
          loop:
            -
              function: "pickProduct"
            -
              get:
                url: "/products/search?query={{ keyword }}"
                headers:
                  Authorization: "Bearer {{ access_token }}"
                capture:
                  json: "$.products[0].code"
                  as: "product_code"
```

breaks with  

```
{
  http request: {
  "method": "FUNCTION",
  "headers": {
    "user-agent": "artillery 2.0.4-0 (https://artillery.io)"
  }
} +1ms
  http Error: options.uri is a required argument
    at Request.init (/tmp/occload/node_modules/request/request.js:246:31)
    at new Request (/tmp/occload/node_modules/request/request.js:142:8)
    at request (/tmp/occload/node_modules/request/index.js:55:10)
    at done (/tmp/occload/node_modules/artillery-core/lib/engine_http.js:314:9)
    at /tmp/occload/node_modules/async/lib/async.js:52:16
    at iterate (/tmp/occload/node_modules/async/lib/async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (/tmp/occload/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/tmp/occload/node_modules/async/lib/async.js:214:22)
    at f (/tmp/occload/node_modules/artillery-core/lib/engine_http.js:196:11)
    at fn (/tmp/occload/node_modules/async/lib/async.js:746:34) +0ms
  runner Error: options.uri is a required argument
    at Request.init (/tmp/occload/node_modules/request/request.js:246:31)
    at new Request (/tmp/occload/node_modules/request/request.js:142:8)
    at request (/tmp/occload/node_modules/request/index.js:55:10)
    at done (/tmp/occload/node_modules/artillery-core/lib/engine_http.js:314:9)
    at /tmp/occload/node_modules/async/lib/async.js:52:16
    at iterate (/tmp/occload/node_modules/async/lib/async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (/tmp/occload/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/tmp/occload/node_modules/async/lib/async.js:214:22)
```
