### ISSUE TITLE
Namespace support?

### ISSUE THREAD

**Issue by menzow** [shoreditch-ops/artillery#218]
Hey,

I'm trying to load test my application using artillery and socket.io.
In the emit action I see that there is a channel attribute, but no namespace attribute.

How do we handle this?

**Comment by hassy** [comment]
Does specifying the namespace in the target URL not work @menzow?

**Comment by menzow** [comment]
Hey @hassy , thanks for your fast response.

Putting the namespace in the target url works indeed. The problem is that I can only test commands to one namespace at a time, and I need to communicate in multiple namespaces during the same test.

I went through artillery-core - `engine_socketio.js`, and it appears a connection is established in the compile method. I'm trying to modify the engine to allow socket connections to be established in the `step` method.

Config could then look something like this:
```
config:
  target: http://localhost:3000/notifications
  phases:
  - duration: 1
    arrivalRate: 1
scenarios:
- engine: socketio
  flow:
  - emit:
      namespace: "/auth"
      channel: "authenticate-user"
      data:
        token: pGxjxhVlv4CA28qN3Id23TxxIslP5meF

  - emit:
      namespace: "/notifications"
      channel: "notifications-list"
  ```

The step method should attempt to re-use or re-establish a new socket connection to the given namespace before emitting the data to the given channel.

Establishing connections would look something like this:
```
SocketIoEngine.prototype.step = function(requestSpec, ee) {
    let namespace = requestSpec.emit.namespace||"/"
    this.getSocket(namespace, function(socketio){ ... rest of step execution ... });
}

SocketIoEngine.prototype.getSocket = function(namespace, cb) {
    if(!this.namespaces[namespace]){
         this.namespaces[namespace] = io.connect(this.config.target + namespace);
         this.namespaces[namespace].on('connect', function(){
               cb(this.namespaces[namespace]);
         }         
   } else {
        cb(this.namespaces[namespace])
   }
}
```

These are my current thoughts on how it could be implemented, there's a  lot more error handling etc that should be done, but I'm not sure what exactly yet..

Could you maybe point me further in the right direction?
