### ISSUE TITLE
Feature: Route reports - log of routes and times

### ISSUE THREAD

**Issue by eshinFG** [shoreditch-ops/artillery#231]
Thank you for creating this stress test tool! 

Would be great if I could see which route/s is taking the longest where. 

Log of times and routes and other useful data in a report form.

Thank you!

**Comment by hassy** [comment]
Definitely a useful feature that should be built in. 👍 

In the meantime this can be accomplished with a little bit of custom JS:

```yaml
- post:
    url: "/some/resource"
    json:
     some: "data"
    name: "Name the route for reports"
    beforeRequest: ["recordStartTime"]
    afterResponse: ["reportLatency"]
```

```javascript
function recordStartTime(req, context, events, done) {
  context.vars._startTime = Date.now();
  return done();
}

function reportLatency(req, res, context, events, done) {
  if (context.vars._startTime) {
    var delta = Date.now() - context.vars._startTime;
    events.emit('customStat', { stat: `latency for ${req.name || req.url}`, value: delta });
  }
  return done();
}
```

Untested, but should work.
