### ISSUE TITLE
Specifying default request parameters

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#239]
It should be possible to set default request parameters with:

```yaml
config:
  http:
    defaults:
      headers:
        'X-Custom-Header': '123'
      followRedirects: false
```
