### ISSUE TITLE
Arrival rate drop issue for specific numbers [TypeError: size must be a number >= 0]

### ISSUE THREAD

**Issue by DavidBonsant** [shoreditch-ops/artillery#243]
Trying to simulate peaks with highs and lows gave us an error, we tested 15 to 5 for 2 minutes and 10 seconds, any other number than 15 to 5 seemed to work, a 100 second duration works too.
here is a sample code that causes the error
```
phases:
  -
    duration: 10
    arrivalRate: 5
    rampTo: 15
  -
    duration: 10
    arrivalRate: 15
  - 
    duration: 10
    arrivalRate: 5

```
