### ISSUE TITLE
Test Login Scenario with CSRF field

### ISSUE THREAD

**Issue by endrureza** [shoreditch-ops/artillery#247]
How can i do test login scenario with csrf field in it ? like laravel or ci..

This is so far the code that i wrote

```
config:
  target: "http://aimsis-exam.dev"
  phases:
    -
      duration: 10
      arrivalRate: 200
  payload:
    path: "user.csv"
    fields:
      - "username"
      - "password"
scenarios:
  -
    name: "Access Page with Autoplay Music"
    flow:
      -
        get:
          url: "/test"
  -
    name: "Access Exam Web"
    flow:
      -
        post:
          url: "/login"
          body: "user={{ username }}&pass={{ password }}"
```
