### ISSUE TITLE
Using {{ variable }} as Int variable 

### ISSUE THREAD

**Issue by maximveksler** [shoreditch-ops/artillery#250]
I can't do that 

`"sender_id": {{ fbID }},` as it complains on an invalid json.

Doing this `"sender_id": "{{ fbID }}",` fails the API, as now the number is a string. 

Any solution for this ?

**Comment by ngbravo** [comment]
Well, `"sender_id": {{ fbID }}` is not valid JSON

**Comment by paulbes** [comment]
I have encountered a similar problem, I ended up solving it in the following way:
`conversion.js`:
```js
function convertIDToInt(requestParams, context, ee, next) {
    requestParams.json.id = parseInt(requestParams.json.id)
    return next();
}
```
`scenario.yaml`
```yaml
config:
  environments:
    dev:
      target: http://localhost:8080
  phases:
    -
      duration: 1
      arrivalRate: 1
  processor: "conversion.js"
  variables:
    id:
      - "1"
scenarios:
  -
    name: "Convert id to int"
    flow:
      -
        get:
          url: "/api/v1/something/{{ id }}"
          beforeRequest: "convertIDToInt"
          json:
            id: "{{ id }}"
```

**Comment by maximveksler** [comment]
@paulbes that's very nice! I was looking for a hook to plug something like convertIDToInt but couldn't find one. 

I ended up using https://github.com/wg/wrk but might look at it again for my next project.

**Comment by hassy** [comment]
A nice way to solve this would be with YAML tags, so you could do something like:

```yaml
- post:
  url: "/some/url"
  json:
    field: !Number "2"
```

But that requires some changes to YAML parsing inside Artillery.

**Comment by yug95** [comment]
you can use as 
 json:
         name: "{{name}}" 
         age: **!!int** "{{age}}"
         state: "{{state}}"
         country: "{{country}}"

!!int make as integer

**Comment by rafayaleem** [comment]
I couldn't find this documented:
```yaml
variables:
    idTest:
      - "1"
```
works but
```yaml
variables:
    id-test:
      - "1"
```
doesn't.

**Comment by hassy** [comment]
that's a great solution @jordandlaman, we'll prioritize getting this sorted properly without needing to resort to writing custom JS

**Comment by tiffanywilson** [comment]
@hassy +1 this! We are writing a lot of our new services in Go and have discovered that the custom js functions can alter the response times recorded (which I realize is a separate issue). But it would be great to be able to pass in arrays of integers.

**Comment by hassy** [comment]
The most recent version of Artillery will now preserve the type of the variable rendered by a template if that's the only operation in that template, so in the something like the following:

```yaml
    flow:
      -
        post:
          url: "/api/v1/something/{{ id }}"
          json:
            id: "{{ id }}"
```

If id = 42, the resulting JSON payload sent to the target will be:

```javascript
{"id": 42}
```

@tiffanywilson Mind opening another issue about the custom JS stuff? very curious
