### ISSUE TITLE
Socket.io Test Giving Error "an URL must be specified"

### ISSUE THREAD

**Issue by danielmeng07** [shoreditch-ops/artillery#254]
Hey guys, I've been stuck on this for a couple days. I simplified it to match the example but it's still not working. When I run the script, it's neither registering on our Nginx access nor our error logs. Did I miss something obvious? Are you guys still supporting Socket.io?

Node 7.4.0
Artillery 1.5.0
Socket.io 1.7.2

test.yaml:
```
config:
  target: "https://sub.mydomain.com/api/socket"
  engine: "socketio"
  phases:
    - duration: 10
      arrivalRate: 1
scenarios:
  - name: "Connect"
    flow:
      - emit:
          channel: "room:join"
          data:
            room_id : "dsflj80c0311111"
```

Output:
```
Complete report @ 2017-02-05T04:25:43.980Z
  Scenarios launched:  10
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    Connect: 10 (Infinity%)
  Errors:
    an URL must be specified: 10
```

**Comment by hassy** [comment]
`engine: "socket.io"` needs to be specified in the scenario definition

**Comment by danielmeng07** [comment]
Okay, I changed the position of the engine declaration and it's now showing up on the access logs. 
In the first 20s, report gave this error: 

```
Errors: xhr poll error: 8
```

Is there something I need to do to for the scenario to complete?

```
Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  Concurrent users:    -10
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
 
```

**Comment by hassy** [comment]
`xhr poll error` is a Socket.io error and based on a quick Google search it doesn't seem like there's a definitive cause for it, but it could do with the server becoming overloaded.

**Comment by danielmeng07** [comment]
Hmm. I doubt that the server is becoming overloaded. My manual load test (by recursively adding clients) ran at about 10 new connections per second for 30 seconds without any hiccups. 

Few things:
1) Connections are not being registered on Node in fact. Could it be that I have a reverse proxy installed on the server? i.e. Requests are rerouted to the server's localhost. (I can provide my Nginx Config if need be)

2) What does the negative concurrent users mean? 

3) Is there anything special I need to do to get numbers to show up in the scenario duration and request latency fields?

**Comment by hassy** [comment]
Yes your reverse proxy could be an issue. Negative users being reported looks like an Artillery bug. You should see some numbers reported when the test runs successfully, the error you're seeing must be preventing any virtual users from executing their scenarios.

**Comment by hassy** [comment]
Closing for now as unclear if it's an issue in Artillery.

**Comment by dolphub** [comment]
@dmr07 I know this is older but were you able to get this working behind a reverse proxy?
I'm using an ingress controller in kubernetes load balancing my socket server.

I have the webapp and the socket server served / scaled separately so I need to use a query path for the socket connection.
```
Report for the previous 10s @ 2018-08-10T20:43:59.859Z
  Scenarios launched:  8
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Errors:
    xhr poll error: 8
```

```
config:
  target: "http://dev.server/"
  socketio:
    transports: ["websocket"]
    query:
      path: "/ws/socket.io"
```
My socket server is proxied through `/ws`
