### ISSUE TITLE
Cannot read property 'capture' of null

### ISSUE THREAD

**Issue by philjones88** [shoreditch-ops/artillery#283]
Getting a weird error.

Both the YAML files I've written error with:

```
/usr/src/app/node_modules/artillery/lib/commands/run.js:200
          if ((params.capture && params.capture.xpath) ||
                     ^

TypeError: Cannot read property 'capture' of null
    at /usr/src/app/node_modules/artillery/lib/commands/run.js:200:22
    at Array.forEach (native)
    at /usr/src/app/node_modules/artillery/lib/commands/run.js:198:23
    at Array.forEach (native)
    at checkIfXPathIsUsed (/usr/src/app/node_modules/artillery/lib/commands/run.js:197:32)
    at fn (/usr/src/app/node_modules/async/lib/async.js:746:34)
    at /usr/src/app/node_modules/async/lib/async.js:1213:16
    at /usr/src/app/node_modules/async/lib/async.js:166:37
    at /usr/src/app/node_modules/async/lib/async.js:706:43
    at /usr/src/app/node_modules/async/lib/async.js:167:37
error Command failed with exit code 1.
```

Even the one without any captures defined.

`node: 7.7.1`

This is what my YAML file looks like:

```
config:
  target: "https://localhost"

  tls: 
    rejectUnauthorized: false

  phases:
    - name: "10 users over 60 seconds"
      duration: 60
      arrivalCount: 10

  payload:
    path: "../../users.csv"
    fields:
      - "id"
      - "username"
      - "password"
    order: "sequence"

scenarios:
  - name: "Visit"
    flow:
      - get:
        url: "/login.html"

      - post:
        url: "/api/authenticate/login"
        json:
          username: "{{ username }}"
          password: "{{ password }}"

      - get:
        url: "/index.html"

      - loop:
          - get:
            url: "/api/foo"
          - think: 5
        count: 12

```

But weirdly, if I rewrite it as the following it works?!

```

config:
  target: "https://localhost"

  tls: 
    rejectUnauthorized: false

  phases:
    -
      name: "10 users over 60 seconds"
      duration: 60
      arrivalCount: 10

  payload:
    path: "../../users.csv"
    fields:
      - "id"
      - "username"
      - "password"
    order: "sequence"

scenarios:
  -
    name: "Visit"
    flow:
      -
        get:
          url: "/login.html"

      -
        post:
          url: "/api/authenticate/login"
          json:
            username: "{{ username }}"
            password: "{{ password }}"

      -
        get:
          url: "/index.html"

      -
        loop:
          -
            get:
              url: "/api/foo"
          -
            think: 5
        count: 12
```
