### ISSUE TITLE
Latency on first few seconds of scenarios issue

### ISSUE THREAD

**Issue by philjones88** [shoreditch-ops/artillery#287]
I've been trying to figure out what is causing this weird initial spike in latency.

I wrote some logic to load the report.json and run jasmine against it so I can easily write unit tests.

The problem is this initial spike in latency seems to fail my tests.

Look at the graphs below. I also wrote something to turn the 10 second intervals in the JSON into CSV so I could graph it in Excel.

This is all running in docker, in the same docker network, on the same fast xeon server so the only latency is our product's processing time.

Have you encountered anything like this?

![image](https://cloud.githubusercontent.com/assets/677167/24508830/9c781936-155c-11e7-8f82-7a8994a78d76.png)

The scenario is quite simple:

```
config:
  target: "https://localhost"

  tls: 
    rejectUnauthorized: false

  phases:
    -
      name: "10 users over 60 seconds"
      duration: 60
      arrivalCount: 10

  payload:
    path: "../../users.csv"
    fields:
      - "id"
      - "username"
      - "password"
    order: "sequence"

scenarios:
  -
    name: "Simple"
    flow:
      -
        get:
          url: "/login.html"

      -
        post:
          url: "/api/authenticate/login"
          json:
            username: "{{ username }}"
            password: "{{ password }}"

      -
        get:
          url: "/index.html"

      -
        loop:
          -
            get:
              url: "/api/foo"
          -
            think: 5
        count: 12
```
