### ISSUE TITLE
[Support request] How to use cheerio selector

### ISSUE THREAD

**Issue by subhojit777** [shoreditch-ops/artillery#299]
I want to capture some data data from post request. I am using this:

```yml
    - post:
        url: "/some/path"
        json:
          color[color_selection]: blue
        capture:
          selector: "$('.some-class').text()"
          as: "testData"
    - {"log": "Captured token is: {{ testData }}"}
```

But I get this error:

```
TypeError: Cannot read property 'parent' of undefined
```

What could be the problem?
