### ISSUE TITLE
No cookie information while debugging http requests

### ISSUE THREAD

**Issue by subhojit777** [shoreditch-ops/artillery#300]
```yml
    - get:
        url: "some/url"
        cookie:
          cookie1: cookie1-value
          cookie2: cookie2-value
```

And the http request is like this:
```
http request: {
  "url": "http://www.local.com/some/url",
  "method": "GET",
  "headers": {
    "user-agent": "artillery 4.0.3 (https://artillery.io)"
  }
}
```

There is no cookie info.
