### ISSUE TITLE
Variables for namespace in the socketio engine are not randomized

### ISSUE THREAD

**Issue by HeyZoos** [shoreditch-ops/artillery#312]
**node**: 6.10.3
**socket.io**: 2.0.2 

Variables for the socketio `namespace` seem to be substituted with a single random choice at the start, but then stays the same throughout. This is not the same behavior exhibited by variables for values of `url` keys.

This is the expected, continually random substitution. 

##### http.yml
```yml
config:
  target: "http://localhost:8000"
  phases:
    -
      duration: 10
      arrivalRate: 1

  variables:
    foo:
      - "foo"
      - "bar"
      - "baz"

scenarios:
  -
    flow:
      -
        get:
          url: "/?foo={{ foo }}"
```

Watching the requests made to an http server produces the following output:

```
python -m http.server 8000
```

```
127.0.0.1 - - [18/Jun/2017 17:32:13] "GET /?foo=bar HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:14] "GET /?foo=bar HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:15] "GET /?foo=baz HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:16] "GET /?foo=baz HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:17] "GET /?foo=bar HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:18] "GET /?foo=baz HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:19] "GET /?foo=foo HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:20] "GET /?foo=baz HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:21] "GET /?foo=foo HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2017 17:32:22] "GET /?foo=foo HTTP/1.1" 200 -
```

Here's how I produce the other substitution behavior:

##### sockets.yml
```yml
config:
  target: "http://localhost:3000"
  phases:
    -
      duration: 10
      arrivalRate: 1

  variables:
    foo:
      - "foo"
      - "bar"
      - "baz"

scenarios:
  -
    engine: "socketio"
    flow:
      -
        emit:
          namespace: "/?foo={{ foo }}"
```

##### simplesockets.js
```javascript
var http = require('http')
var app = http.createServer();
var io = require('socket.io').listen(app);

io.on('connection', function(socket) {
  if (socket.handshake.query.foo) {
    console.log(socket.handshake.query.foo);
  }
});

app.listen(3000);
```

When this is run against the simple socketio server, I get the following output:

```
bar
bar
bar
bar
bar
bar
bar
bar
bar
bar
```

If I try again I get:

```
baz
baz
baz
baz
baz
baz
baz
baz
baz
baz
```

I apologize if I missed something really obvious, this behavior just struck me as odd.
