### ISSUE TITLE
log messages not printing to console and issues with http match documentation

### ISSUE THREAD

**Issue by dannomayer** [shoreditch-ops/artillery#317]
Hi there,

I'm very new to all of this, so I am probably just missing something, but I've encountered what seems to be an issue with the [documentation referring to capturing and matching in an http request](https://artillery.io/docs/testing_http.html#extract-and-reuse-parts-of-a-response-request-chaining).

Allow me to explain:

Im creating a basic acceptance test with matching very tightly based on the example code you've provided that includes matching. Using [json-server](https://github.com/typicode/json-server) I've setup a local server that allows me to get and post (and more that I do not use). The code I expect to work is below:

```
config:
  # this hostname will be used as a prefix for each URI in the flow unless a complete URI is specified
  target: 'http://localhost:3000'
  phases:
    -
      duration: 1
      arrivalRate: 1
scenarios:
    - flow:
      - post:
          url: "/posts"
          json:
            title: "tests"
          log: "{{ title }}"
          capture:
            json: "$.id"
            as: "id"
      - get:
          url: "/posts/{{ id }}"
          match:
            json: "$.title"
            value: "{{ title }}"
```

I expect this code to log one match. It logs none. I run the script with http debuggers and artillery spits this out:

 ```
  ~/acceptanceTests/test $ DEBUG=http* artillery run DocumentationBasedScript.yml 
  Log file: artillery_report_20170706_145998.json
  
  Phase 0 started - duration: 1s
   -  http request: {
    "url": "http://localhost:3000/posts",
    "method": "POST",
    "headers": {
      "user-agent": "Artillery (https://artillery.io)"
    },
    "json": {
      "title": "tests"
    }
  } +0ms
    http:response {
    "x-powered-by": "Express",
    "vary": "Origin, X-HTTP-Method-Override, Accept-Encoding",
    "access-control-allow-credentials": "true",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "expires": "-1",
    "access-control-expose-headers": "Location",
    "location": "http://localhost:3000/posts/54",
    "x-content-type-options": "nosniff",
    "content-type": "application/json; charset=utf-8",
    "content-length": "34",
    "etag": "W/\"22-Rv7f5lVZowFLgjJgsyhR/4/xfuA\"",
    "date": "Thu, 06 Jul 2017 21:59:40 GMT",
    "connection": "keep-alive"
  } +1ms
    http:response {
    "title": "tests",
    "id": 54
  } +1ms
    http captures and matches: +3ms
    http {} +1ms
    http { id: 54 } +1ms
    http request: {
    "url": "http://localhost:3000/posts/54",
    "method": "GET",
    "headers": {
      "user-agent": "Artillery (https://artillery.io)"
    }
  } +12ms
    http:response {
    "x-powered-by": "Express",
    "vary": "Origin, Accept-Encoding",
    "access-control-allow-credentials": "true",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "expires": "-1",
    "x-content-type-options": "nosniff",
    "content-type": "application/json; charset=utf-8",
    "content-length": "34",
    "etag": "W/\"22-Rv7f5lVZowFLgjJgsyhR/4/xfuA\"",
    "date": "Thu, 06 Jul 2017 21:59:40 GMT",
    "connection": "keep-alive"
  } +0ms
    http:response "{\n  \"title\": \"tests\",\n  \"id\": 54\n}" +0ms
    http captures and matches: +1ms
    http { '$.title': { success: false, expected: '', got: 'tests', expression: '$.title', strict: undefined } } +0ms
    http {} +1ms
  
  Report for the previous 10s @ 2017-07-06T21:59:41.068Z
    Scenarios launched:  1
    Scenarios completed: 0
    Requests completed:  2
    RPS sent: 4
    Request latency:
      min: 4.3
      max: 10.2
      median: 7.3
      p95: NaN
      p99: NaN
    Scenario duration:
      min: NaN
      max: NaN
      median: NaN
      p95: NaN
      p99: NaN
    Codes:
      200: 1
      201: 1
  
  all scenarios completed
  Complete report @ 2017-07-06T21:59:41.072Z
    Scenarios launched:  1
    Scenarios completed: 0
    Requests completed:  2
    RPS sent: 4
    Request latency:
      min: 4.3
      max: 10.2
      median: 7.3
      p95: NaN
      p99: NaN
    Scenario duration:
      min: NaN
      max: NaN
      median: NaN
      p95: NaN
      p99: NaN
    Scenario counts:
      0: 1 (100%)
    Codes:
      200: 1
      201: 1
 ```
 Two issues here..
 1. The match is not successful and says it expected ''. So, it seems like the attempt to set value to the title variable within the match is failing.
 2. I don't see a log message anywhere. Neither in the report nor console. Documentation specifies it will print to console.
 
I was able to get the match to be successful with the following script:

```
config:
  # this hostname will be used as a prefix for each URI in the flow unless a complete URI is specified
  target: 'http://localhost:3000'
  phases:
    -
      duration: 1
      arrivalRate: 1
scenarios:
    - flow:
      - post:
          url: "/posts"
          json:
            title: "tests"
          capture:
            json: "$.id"
            as: "id"
      - get:
          url: "/posts/{{ id }}"
          match:
            json: "$.title"
            value: "tests"
```
The output to the console, using the same debug setup, is identical as far as I can tell except for two lines. The report notes that the scenario is completed and the match shows:

`  http { expr: { success: true, expected: 'tests', expression: '$.title' } } +0ms`

All I change from the first script is the last line, in which I specify the string I am trying to match because the variable {{ tests }} does not appear to register. Weird because id does and they are both in the get. Has anyone run into this before or am I doing something wrong or is this a bug? I am having trouble following the source code to see exactly what it is doing/expecting as input. Like I said, I am new to both web dev and artillery. Help and clarification would be very appreciated!

**Comment by hassy** [comment]
You aren't actually creating a `title` variable in your first example as far as I can see. You're sending a JSON payload in your first POST request where a *field* "title" is set to the string "title", but a variable called `title` isn't defined anywhere, so in the `match` expression `$.title` is compared to an empty string.

Re `log` - it's not an attribute of a request, but a separate action, i.e. this should work:

```yaml
- get:
  url: "/some/url"
- log: "something"
```

**Comment by dannomayer** [comment]
This is true, however it looks like documentation demonstrates that this is possible.. Just so you know :P Once again... I immediately yield I am likely incorrect, but I pasted the section I'm talking about below...

```
In the following example, we POST to /pets to create a new resource, capture part of the response (the id of the new resource) and store it in the variable id. We then use that value in the subsequent request to load the resource and to check to see if the resource we get back looks right.

-
  post:
    url: "/pets"
    json:
      name: "Mali"
      species: "dog"
    capture:
      json: "$.id"
      as: "id"
-
  get:
    url: "/pets/{{ id }}"
    match:
      json: "$.name"
      value: "{{ name }}"
By default, every response body is captured in the variable $, so the example above could also be rewritten as:

-
  post:
    url: "/pets"
    json:
      name: "Mali"
      species: "dog"
-
  get:
    url: "/pets/{{ $.id }}"
    match:
      json: "$.name"
      value: "{{ name }}"
```

On the other hand, the log is working now... Many thanks!

Here is a script I just ran that still doesn't print the `type` variable (still just an empty string). Is it still defined incorrectly?

```
config:
  # this hostname will be used as a prefix for each URI in the flow unless a complete URI is specified
  target: 'https://jdukuvpem8.execute-api.us-east-1.amazonaws.com/beta'
  phases:
    -
      duration: 5
      arrivalRate: 1
#      rampTo: 2
scenarios:
    - flow:
      - post:
          url: "/pets"
          json:
            type: "fish"
            price: "5.01"
          capture:
            json: "$.id"
            as: "id"
            json: "$.type"
            as: "type"
      - get:
          url: "/pets/{{ id }}"
      - log: "{{ type }}"
```

I find it odd that the id variable works as intended but type does not... any idea what's going on here?


Thanks again for the help, really enjoying using artillery!!
