### ISSUE TITLE
Is it possible to force websockets transports only?

### ISSUE THREAD

**Issue by plumpNation** [shoreditch-ops/artillery#335]
I'm writing a server for swift apps using the socket.io-client-swift library.

I do not want to allow long polling at this time, but if I set the server to only accept websockets, then start a load test, the debug output simply fills with `socketio Error: xhr poll error`.

Is there somewhere I can pass in the transport to the socketio engine in artillery?

**Comment by hassy** [comment]
You should be able to set `config.socketio.transports`, e.g.:

```yaml
config:
  target: "something"
  socketio:
    transports: ["websocket"]
scenarios:
  # ...
```
