### ISSUE TITLE
Log messages not working with the "ws" engine.

### ISSUE THREAD

**Issue by Cristy94** [shoreditch-ops/artillery#342]
```
scenarios:
    - engine: "ws"
      flow:
        log: "WTF"
```

The above results in an error:
```
TypeError: Cannot read property 'toString' of undefined
\artillery-core\lib\engine_ws.js:64:24)
...
   at emitNone (events.js:105:13)
    at WebSocket.emit (events.js:207:7)
/ Unexpected error, Artillery shutting down.
```

I think that atm `ws` is broken, it (for some reason) automatically sends a message with payload `undefined` when it connects, but this breaks things because it's trying to call `undefined.toString()`.

**Comment by hassy** [comment]
The scenario should look like:

```yaml
- engine: ws
  flow:
    - log: "Hello"
```

`flow` is expected to be an array, not an object.
