### ISSUE TITLE
formData is not mentioned in the documentation.

### ISSUE THREAD

**Issue by ecker00** [shoreditch-ops/artillery#343]
The documentation has a lot of examples with json post, but nothing mentioning the formData method, which is needed for a PHP backend to fetch the data in $_POST. I am not sure if I'm familiar enough with artillery yet to contribute the necessary changes.

```yml
scenarios:
  - name: 'Sign in and navigate'
    flow:
      - post:
          url: '/'
          formData: 
            signin: 'true'
            username: 'myUsername'
            password: 'myPassword'
      - get:
          url: '/profile'
```
