### ISSUE TITLE
Question: constant load with phases

### ISSUE THREAD

**Issue by sberserker** [shoreditch-ops/artillery#345]
How to replicate this quick command parameters using phases:
artillery quick **--count 10 -n 20** https://artillery.io/

10 "virtual users" each of which will send 20 HTTP. What should be in phases to replicate that?
 phases:

**Comment by hassy** [comment]
```
config:
  phases:
    - arrivalCount: 10
      duration: 1
scenarios:
  - flow:
    - loop:
        - get: "/some/url"
      count: 20
```
