### ISSUE TITLE
graphical presentations + 10 secs duration

### ISSUE THREAD

**Issue by binarytracer** [shoreditch-ops/artillery#346]
**config.yaml.yml**
```yaml
config:
  target: 'http://localhost:3000'
  phases:
    - duration: 50
      arrivalRate: 100 # no of new virtual users / sec
      name: 'Phase 01'
scenarios:
  - name: "Express App (post)"
    flow:
    - post:
        url: "/users"
        json:
          data: "for the sake of testing"
```

![summary1](https://user-images.githubusercontent.com/8814442/29656682-be3cef52-88e7-11e7-99ab-7e8f06602a70.png)

Graphs

![graphical-presentation](https://user-images.githubusercontent.com/8814442/29656731-eb9f3ff4-88e7-11e7-9e3d-e4f68870cbb4.png)

it has to be on **50** only, right? as indicated on **config.yaml.yml**
