### ISSUE TITLE
Integration Support?

### ISSUE THREAD

**Issue by tylerbhughes** [shoreditch-ops/artillery#352]
Does Artillery support integrations? Let's say I wanted to give Artillery support for making SOAP requests but didn't want to contribute directly to the project. Does Artillery have an integration API that makes this possible? If yes, can someone point me to the documentation for it?

**Comment by hassy** [comment]
Yes it's possible and several users have built custom engines but the documentation is lacking at the moment unfortunately. Artillery tries to dynamically load engines with non-default names, e.g. given the following scenario:

```yaml
config:
  # config here
scenarios:
  - name: "My scenario"
    engine: "custom" # custom engine
    flow:
      - someaction: "something"
```

Artillery will try to `require('artillery-engine-custom')` (ref: https://github.com/shoreditch-ops/artillery-core/blob/master/lib/runner.js#L99)

The WebSocket engine is quite small and would be a good place to start to understand how engines work: https://github.com/shoreditch-ops/artillery-core/blob/master/lib/engine_ws.js

Also the basic tests for the HTTP engine could be useful: https://github.com/shoreditch-ops/artillery-core/blob/master/test/unit/engine_http.test.js#L47-L55
