### ISSUE TITLE
Http-Only Cookies not always attached to requests

### ISSUE THREAD

**Issue by brettveenstra** [shoreditch-ops/artillery#354]
We have an authentication system as part of load test where a dynamic HTTP-only cookie is required to retrieve a JWT token.

In our Token system, we are seeing requests where the cookie is not provided consistently with new requests.  We are seeing this occurrence rate of about 4 in 2500 requests

For reference, we are using the `pool` setting (set at 30), two `payload` files, and only one `phase` as:

      - duration: 300
        arrivalCount: 4000

Our Scenario looks like:

    flow:
    - post:
        url: '/auth'
        json:
          userName: '{{ username }}'
          password: '{{ password }}'
    # NOTE: an HTTP-Only cookie is returned in the ^^ request, and must be sent to the following step
    - post:
        url: '/genToken'
        capture:
          json: 'accessToken'
          as: 'accessToken'
    - get:
        url: '/search'
        headers:
          Authorization: 'Bearer {{accessToken}}'

**Comment by hassy** [comment]
Interesting, thanks for the report @brettveenstra. Have you ruled out the possibility that the server isn't setting the cookie on some responses? That could be verified with [a custom function](https://artillery.io/docs/http-reference/#advanced-writing-custom-logic-in-javascript), something like:

```javascript
function checkCookie(req, res, userContext, events, next) {
  if(!res.headers['set-cookie']) {
    console.log(`No cookie set for ${req}`);
  }
  return next();
} 
```

and invoke it in the scenario with a `function` action:

```yaml
flow:
- post:
    url: '/auth'
    json:
      userName: '{{ username }}'
      password: '{{ password }}'
    afterResponse: "checkCookie" # check that we have a cookie
# NOTE: an HTTP-Only cookie is returned in the ^^ request, and must be sent to the following step
- post:
    url: '/genToken'
    capture:
      json: 'accessToken'
      as: 'accessToken'
- get:
    url: '/search'
    headers:
      Authorization: 'Bearer {{accessToken}}'
```

**Comment by hassy** [comment]
Closing for now, feel free to re-open with more information @brettveenstra.

**Comment by brettveenstra** [comment]
@hassy - thanks for the tip!  Found issue with our service... one additional question though...

How can I gracefully prevent the `/genToken` and `/search` steps from running in the flow?  That is, I'd like to be able to make the processor quit out of a `flow` on a certain response status code...  I'll make a new Issue if you'd prefer to answer there.

**Comment by hassy** [comment]
There's a couple of options:

1) If you're running an `afterResponse` function, calling back with an `Error` will stop the flow at the current request.
2) Use the (undocumented) `ifTrue` attribute, which will make Artillery execute a request only if a variable is defined, e.g.:

```
- post:
    url: "/some/url"
    json:
      hello: "world"
    ifTrue: "someVariable" # where someVariable refers to a variable captured (or not) in the previous request for example
```
