### ISSUE TITLE
Random data and query not working

### ISSUE THREAD

**Issue by andrewpros** [shoreditch-ops/artillery#359]
Hi.
Haven't found any way to do this i need to provide query with an object containing user data, login, id etc. it can be random, but the random functions doesn't work in query or i'm doing something wrong.

My config

```yaml
config:
  target: "http://server.web:8876"
  phases:
    - duration: 10
      arrivalRate: 5
  socketio:
   query: {id: '', avatar: '', login: '', room: '', reconnect: false}
scenarios:
  - name: "A user that just lurks"
    engine: "socketio"
    flow:
      - get:
          url: "/"
      - emit:
          channel: "lobby"
          data: "lurker-{{ $randomString(10) }}"
      - think: 60
```

I appreciate any help with this or is there a way i can rewrite the chat to get the user data not from query object?
