### ISSUE TITLE
socket.io just connect

### ISSUE THREAD

**Issue by MickL** [shoreditch-ops/artillery#361]
Im struggly with the documentation a little bit. I JUST want to connect without any channel or emitting data and keep the connection alive. Is this even possible?

**Comment by hassy** [comment]
Yes, use a `think` command to keep the connection open without sending anything.

**Comment by MickL** [comment]
I tried the following with no success:

```
config:
  target: "http://localhost:3000"
  phases:
    - duration: 10
      arrivalRate: 1

scenarios:
    - engine: "socketio"
      flow:
        - think: 10
```

I don't see any connections on my server and Artillery says:

```
Summary report @ 14:44:33(+0200) 2017-09-07
  Scenarios launched:  10
  Scenarios completed: 0
  Requests completed:  0
  Concurrent users:    3
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 10 (100%)
  Errors:
    Error: xhr poll error: 10

```

**Comment by hassy** [comment]
You're not seeing connections because of the `xhr poll error` error most likely. Can you try rerunning your test with the following added to config:

```
config:
  socketio:
    transports: ["websocket"]
```

**Comment by MickL** [comment]
Thank it is working as expected now! Final script:

```
config:
  target: "http://localhost:3000"
  phases:
    - duration: 500
      arrivalRate: 25 # 25 is the maximum before a single cpu-core goes to high (AWS EC2 m3.xlarge)
  socketio:
    transports: ["websocket"]

scenarios:
    - engine: "socketio"
      flow:
        - think: 3600
```

**Comment by MickL** [comment]
@hassy Thanks for updating the documentation, this helps alot! 
What about socket.io's `on`? Do i have to create a js-function? Im looking for something like:

```
scenarios:
    - engine: "socketio"
      flow:
        - on: "message"
           log: "Received message"
        - think: 3600
```
