### ISSUE TITLE
complex payload

### ISSUE THREAD

**Issue by nnnikolay** [shoreditch-ops/artillery#371]
Is there any way to use different payload for different urls in a flow?

for example, by specifying the certain function name for each request from `processor`?

**Comment by hassy** [comment]
Not sure what you mean, do you have a more concrete example?

**Comment by nnnikolay** [comment]
I'm trying to follow the docs from [here](https://github.com/shoreditch-ops/artillery-docs/blob/master/source/testing_http.rst), it looks like I've found what I need, but it does not work yet, will check it out later, maybe it is my mistake.

What I've tried to achieve is the following case 

```
config:
  #
  # configuration section
  #
scenarios:
  - name: "My scenario"
    flow:
      - get:
          url: "/"
      - function: "acquireToken"
      - post:
          url: "/protected/endpont"
        - function: "acquireTokenTwo"
```
