### ISSUE TITLE
Is it possible to customize the config from the command line?

### ISSUE THREAD

**Issue by jordan-brough** [shoreditch-ops/artillery#372]
It would be nice if I could do something like this:

```
config:
  target: "..."
  phases:
    - duration: {{process.env.MY_DURATION}}
      arrivalRate: {{process.env.MY_ARRIVAL_RATE}}
```

So that I don't have to change the yaml contents to produce different test runs.

Is there any way of doing that?

**Comment by hassy** [comment]
There isn't a way to do that, but one option that might work instead is to create different profiles with `config.environments`, e.g. something like:

```yaml
config:
  target: ""
  environments:
    debug:
      target: "http://localhost"
      phases:
        - duration: 1
          arrivalCount: 1
    staging:
      target: "https://staging.dev"
      phases:
        - duration: 600
          arrivalRate: 5
```

and use one of the environments with:

```
artillery run -e debug myscript.yaml
```
