### ISSUE TITLE
Enhancement - Asynchronous requests

### ISSUE THREAD

**Issue by damon-kreft** [shoreditch-ops/artillery#376]
Firstly, great work on Artillery.

Secondly, there doesn't seem to be a way to simulate asynchronous requests. E.g. our React app makes 5 asynchronous calls after initialisation that don't depend on each other and we of course wish to simulate this real-world scenario for each virtual user.

Therefore something like...
```yml
scenarios:
  - name: "My Scenario"
    flow:
      - get:
          url: "/profile/basic"
          async: true
      - get:
          url: "/transactions/recent/{{ accoundId }}"
          async: true
      - get:
          url: "/transactions/pending/{{ accoundId }}"
          async: true
      - get:
          url: "/accountsummary/{{ accoundId }}"
          async: true
```

or

```yml
scenarios:
  - name: "My Scenario"
    flow:
      - async:
        - get:
            url: "/profile/basic"
        - get:
            url: "/transactions/recent/{{ accoundId }}"
        - get:
            url: "/transactions/pending/{{ accoundId }}"
         - get:
            url: "/accountsummary/{{ accoundId }}"
```

I appreciate there is then this issue of one async call depending on the result of another async call, so perhaps...

```yml
scenarios:
  - name: "My Scenario"
    flow:
      - get:
          id: "profile"
          url: "/profile/basic"
          async: true
      - get:
          waitFor: "profile"
          url: "/transactions/recent/{{ accoundId }}"
          capture:
            json: "$.id"
            as: "id"
```

Happy to contribute.
