### ISSUE TITLE
Problem loading .csv data into the .yml file for request body

### ISSUE THREAD

**Issue by bytewiz** [shoreditch-ops/artillery#378]
So the problem is that the "template" variables doesn't get replaced when running the script.

"Real url" scrabled

## home.yml file:
```
config:
    target: "http://someurl.com"
    phases:
      - duration: 1
        arrivalCount: 1
    payload:
      path: "users.csv"
      fields:
        - "email"
        - "password"
      order: "sequence"
    processor: "./log.js"
scenarios:
  - flow: 
    - log: "New virtual user running"
    - post:
        url: "/tokens"
        headers:
          Content-Type: "application/json"
        json:
          email: "{{ email }}"
          password: "{{ password }}"
        beforeRequest: "setJSONBody"
        afterResponse: "logHeaders"
```

## users.csv file: (doesn't matter what the actual data is actually)
```
email,password
my@email.com,awesomePassword
```

## log.js file:
```
module.exports = {
    setJSONBody: setJSONBody,
    logHeaders: logHeaders
  }

  function setJSONBody(requestParams, context, ee, next) {
    console.log(requestParams)
    return next(); // MUST be called for the scenario to continue
  }

  function logHeaders(requestParams, response, context, ee, next) {
    console.log(response.body);
    return next(); // MUST be called for the scenario to continue
  }
```

## Request (when running the test):
```
{ url: 'http://someurl.com/tokens',
  headers: {},
  json: { email: '{{ email }}', password: '{{ password }}' },
  beforeRequest: 'setJSONBody',
  afterResponse: 'logHeaders',
  method: 'POST',
  timeout: 120000,
}
```

As you might notice the template variables: `'{{ email }}'` and `'{{ password }}'` should be replaced by the input data from the `.csv`

What is wrong here?
@hassy by your request I created this issue from the gitter comment I [posted](https://gitter.im/shoreditch-ops/artillery?at=59c93d727b7d98d30d35843b)

If more information is required please let me know.

**Comment by hassy** [comment]
The variables do actually get replaced. `beforeRequest` hooks run before the substitutions happen, that's why you're seeing the templates in the output from your function.

To verify, run `nc -l 10888` in one window, change target to "http://localhost:10888" and run your script. You should see something like:

```
$ nc -l 10888

POST /tokens HTTP/1.1
user-agent: Artillery (https://artillery.io)
content-type: application/json
host: localhost:10888
accept: application/json
content-length: 39
Connection: keep-alive

{"email":"email","password":"password"}
```

**Comment by hassy** [comment]
Going to close this for now @bytewiz but feel free to reopen with more info if you're still seeing the issue.

**Comment by bytewiz** [comment]
@hassy lol you are right... my bad 👍 

And no problem, makes easier for all if there is a reproducible example 💯 

Thanks for the quick reply and an awesome tool 🙌

**Comment by rodrigofariasm** [comment]
This is still happening with me, I am having this problem now.
My problem is, I have a csv file with lines like this 
```
['1234' '23']
```

and my yaml looks like this
``` yaml 
config:
    target: "https://my-url"
    phases:
      - duration : 60
        arrivalRate : 20
    processor: "conversion.js"
    defaults:
        headers:
            Content-Type: "application/json"
    payload:
        path: "oneline.csv"
        fields:
          - "ids_list"
scenarios:
  - flow:
      - post:
          beforeRequest: "convertStrToList"
          url: "/invocations"
          json:
              ids: "{{ ids_list }}"
```

And my conversion processor is this 
``` js
module.exports = {
	convertStrToList : convertStrToList
};
function convertStrToList(requestParams, context, ee, next) { 
    console.log(requestParams)
    requestParams.json.ids = JSON.parse(requestParams.json.ids)
    return next();
};
```
Altough I'm getting this error the line above is the console log of the function
```
Started phase 0, duration: 60s @ 18:33:19(-0300) 2019-05-28
.   { beforeRequest: 'convertStrToList',
  url: 'https://myurl',
  json: { ids: '{{ ids_list }}' },
  method: 'POST',
  headers: {},
  timeout: 120000,
  jar:
   RequestJar {
     _jar: CookieJar { enableLooseMode: true, store: { idx: {} } } } }
undefined:1
{{ ids_list }}
 ^
```

Any help
