### ISSUE TITLE
Connecting to namespaced socket.io target not working

### ISSUE THREAD

**Issue by schuma7** [shoreditch-ops/artillery#386]
I tried to connect to a socket.io endpoint by specifying the target namespace according to the form given in the docs: 

`target: "https://myapp.staging:3002/admin"`

However, the socket just wouldn't connect, so I launched the server with all debug logs enabled and saw that the cause for the issue was an "Invalid Namespace" error. I noticed that the namespace contained a trailing slash, which is not the case when connecting through other clients such as the JavaScript one.

Note that when connecting to the default namespace using:

`target: "https://myapp.staging:3002`

and specifying the namespace in the emit action, everything works as expected though.

```
- emit:
          namespace: "/admin"
          channel: "authenticate"
          data:
            token: "my-token"
```

I'm using Socket.io 2.0.3 and Artillery 1.6.0-10.
