### ISSUE TITLE
Looping over array from captured

### ISSUE THREAD

**Issue by gioragutt** [shoreditch-ops/artillery#392]
```yaml
- get:
      url: "/getAllFilesOfUser/{{ username }}"
      headers:
        Accept: "application/json"
        Authorization: "Bearer {{ token }}"
      capture:
        - json: "$.length"
          as: "questionnairesCount"
        - json: "$.*.content"
          as: "questionnaires"
- log: "Received {{ questionnairesCount }} questionnaires for {{ username }}"
# - log: "BLA BLA {{ questionnaires }}"
- loop:
  - log: "LOOP {{ $loopElement }}"
  over: "questionnaires"
```

The `over` clause, I couldn't get it to work with neither `questionnaires`, `"questionnaires"` or `{{ questionnaires }}`

The expected results is pretty obvious.

**Comment by hassy** [comment]
Are you on the latest version of Artillery (`artillery -V`) and is `questionnaires` definitely an array?

**Comment by gioragutt** [comment]
Yes, it's an array, and I installed artillery just yesterday

**Comment by hassy** [comment]
Can you just confirm the version you have installed please? You might not be on the latest pre-release version. How did you confirm that `questionnaires` is a list?

I'm not saying you haven't encountered a bug in Artillery, but to help us isolate it we need to rule out any possible issues with your environment / script first.

**Comment by gioragutt** [comment]
I'm starting to believe that this is a matter of capture syntax.

I have an array of the following structure:

```json
[
{
    "foo": ...,
    "bar": ...,
    "content"....
},
...
]
```

And I'm trying to get the `content` item from all of them. I've tried `$..*.content`, `$..content`, `$..*.content`, `$..[*].content`, and so on. I just get the first item, regardless of if there are any more.

But if I have a
```yml
capture:
  - json: "$"
    as: "body"
```

I can see the more than one element in the array, aka `[{...}, {...}, ...]`
