### ISSUE TITLE
Using beforeRequest to modify the request object

### ISSUE THREAD

**Issue by runandrew** [shoreditch-ops/artillery#395]
I would like to use a JS file to modify the request json payload before it's sent to the server. But it seems like it doesn't actually effect the request object from what I'm seeing on the server.

My helper JS

```js
const moment = require("moment");

exports.currentTime = (req, context, events, next) => {
  const unixTime = moment()
    .unix()
    .valueOf();

  req.json.timestamp = unixTime;
  return next();
};
```

In my config:

```yaml

...
config:
  processor: "../utils/helpers.js"
...
  - name: "Flow name"
    weight: 2
    flow:
      - post:
          beforeRequest: "currentTime"
          url: "/api/route"
          json:
              timestamp: 123
```

When I look at the request on my server, I'm getting `timestamp` to be `123` and not the current time.

**Comment by hassy** [comment]
Thanks for the bug report @runandrew. Your code should be working, I'll investigate.

**Comment by roback** [comment]
I ran into the same problem. My workaround was to remove `json:` from the config file and then setting `req.json = { timestamp: unixTime }` in the helper JS file instead. (using v.1.6.0-12)

**Comment by vishalbiradar** [comment]
This is the working code.
**context.vars.currentTime = unixTime;**
Using this line in helpers.js file you can access the current time variable in yml file.

helpers.js
----------
```

const moment = require("moment");

exports.currentTime = (req, context, events, next) => {
    const unixTime = moment()
        .unix()
        .valueOf();

    context.vars.currentTime = unixTime;
    return next();
};
```

test.yml
---------
```

...
config:
  processor: "../utils/helpers.js"
...
  - name: "Flow name"
    weight: 2
    flow:
      - post:
          beforeRequest: "currentTime"
          url: "/api/route"
          json:
              timestamp: {{ currentTime }}
      - log: "Time is = {{ currentTime }}"

```
