### ISSUE TITLE
ECONNRESET on several HTTP Request in flow

### ISSUE THREAD

**Issue by cedricherve** [shoreditch-ops/artillery#398]
Hello,

My config:
- Node Js : 3.10.10
- Artillery : 1.6.0-10
- Test context : windows 7

We get an issue when trying to launch several HTTP requests in 1 flow : ECONNRESET

Here is my yaml config

```
config: 
  phases: 
    - arrivalRate: 1
      duration: 3    
  target: "http://my_entry_point"
  headers:
      Content-type: "application/json"
      Accept: "application/json"
scenarios: 
  - flow: 
      - log: "new user running and getting domains"
      - post: 
          url: "/authenticate"
          auth: 
            pass: "login_basic_auth"
            user: "pws_basic_auth"
          json: 
            login: "jhon"
            password: "doe" 
          capture:
            header: "Set-Cookie"
            as: "mycookie"            
      - get: 
          url: "/domains"
          auth: 
            pass: "login_basic_auth"
            user: "pws_basic_auth"     
          headers:
            cookie: "{{mycookie}}}"
```

Then I get the following response in console:

```
set DEBUG=http&&artillery run configArtillery.yml --output report.json&&artillery report report.json
Started phase 0, duration: 3s @ 14:44:36(+0100) 2017-11-03
/ new user running and getting domains
-   http request: {
  "url": "http://my_entry_point/authenticate",
  "method": "POST",
  "headers": {
    "user-agent": "Artillery (https://artillery.io)"
  },
  "json": {
    "login": "jhon",
    "password": "doe"
  }
} +0ms
  http captures and matches: +7ms
  http {} +5ms
  http {} +8ms
  http Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26) +31ms
```

If I only set 1 request in flow (the POST or the GET one), it's ok in report, the pb only occurs when I set both request (POST to authenticate and get the auth cookie then the GET to access to my domains).

Is there a way to debug more verbose logs or is it a know issue ?
