### ISSUE TITLE
Support socket.io acknowledge 

### ISSUE THREAD

**Issue by BigZolo** [shoreditch-ops/artillery#402]
Is it planned to support the acknowledge callback? 
The syntax could be:
```
- emit:
  channel: "echo"
  data: "world"
  response:
     # no channel as it should be the expected ack data
     data: "world"
```

**Comment by cloudratha** [comment]
Seems like acknowledge is already supported.

```yml
- emit:
    channel: "echo"
    data: "world"
    acknowledge:
        data: "world
```

https://github.com/shoreditch-ops/artillery/blob/master/core/lib/engine_socketio.js#L165
