### ISSUE TITLE
Node args for artillery

### ISSUE THREAD

**Issue by jjdp** [shoreditch-ops/artillery#405]
Does it support running with your own node args? I want to use `–max-old-space-size=8192`.  I'm load testing our socket.io server and once i set a pinginterval and timeout of 5s.  GC is giving me a heap out of memory error on artillery after a while. cc @hassy 

Related to https://github.com/shoreditch-ops/artillery/issues/130 ?

Test is pretty simple. only for idle concurrent cons

```
config:
  target:  ""
  socketio:
    transports: ["websocket"]
    query:
      username: "someusername"
  phases:
    - duration: 100
      arrivalRate: 400
scenarios:
  - engine: "socketio"
    flow:
      # do nothing for 1 hour and disconnect
      - think: 3600
```
