### ISSUE TITLE
how to create/view/open graphical report

### ISSUE THREAD

**Issue by vishalbiradar** [shoreditch-ops/artillery#408]
Im first time using artillery, and after following artillery.io site documentation code:
```
config:
  target: 'https://artillery.io'
  phases:
    - duration: 60
      arrivalRate: 20
  defaults:
    headers:
      x-my-service-auth: '987401838271002188298567'
scenarios:
  - flow:
    - get:
        url: "/docs"
```
and then running above code snippet 

$ **artillery run test.yml**

I am unable to see the graphical reports ??
How can see it??
No where, in your documentation you guys mentioned the steps for viewing those reports.
 
Below is the output from my cli:
-------------
<img width="669" alt="screen shot 2017-12-06 at 3 51 33 pm" src="https://user-images.githubusercontent.com/29951629/33656873-858e148a-da9d-11e7-98d8-4fa058b027a0.png">
