### ISSUE TITLE
Setup step with one of requests

### ISSUE THREAD

**Issue by Maddemacher** [shoreditch-ops/artillery#417]
Is it possible to have a setup section with one of requests that provide initial data to the api?

I.e.
```
config:
  target: 'asd.asd.com' 
  .
  .
setup:
  - post:
      url: '/stuff'
      form:
        name: 'best stuff'
scenarios:
  - flow:
    - get:
        url: '/stuff'
 ``` 

where the requests ithin the setup section only fired once
