### ISSUE TITLE
Can not run right with my websocket server

### ISSUE THREAD

**Issue by prettyyjnic** [shoreditch-ops/artillery#419]
Here is my websocket server with golang,
```
package main

import (
	"fmt"
	"log"
	"net/http"
	"golang.org/x/net/websocket"
)

func Echo(ws *websocket.Conn) {
	var err error
	for {
		var reply string
		if err = websocket.Message.Receive(ws, &reply); err != nil {
			fmt.Println("Can't receive")
			break
		}
		fmt.Println("Received back from client: " + reply)
		msg := "Received: " + reply
		fmt.Println("Sending to client: " + msg)
		if err = websocket.Message.Send(ws, msg); err != nil {
			fmt.Println("Can't send")
			break
		}
	}
}

func main() {
	http.Handle("/", websocket.Handler(Echo))
	if err := http.ListenAndServe(":1234", nil); err != nil {
		log.Fatal("ListenAndServe:", err)
	}
}
```
while i use artillery to webbench it, i got error return ! I was confuse with this
```
$ ./bin/artillery run ./bin/web.yml
Started phase 0, duration: 2s @ 11:35:06(+0800) 2018-01-26
Report @ 11:35:08(+0800) 2018-01-26
  Scenarios launched:  2
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Errors:
    undefined: 2

All virtual users finished
Summary report @ 11:35:08(+0800) 2018-01-26
  Scenarios launched:  2
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 2 (100%)
  Errors:
    undefined: 2

```

Here is my yml file
```
config:
  target: "ws://127.0.0.1:1234"
  phases:
    - duration: 2
      arrivalRate: 1
  ws:
    # Ignore SSL certificate errors
    # - useful in *development* with self-signed certs
    rejectUnauthorized: false
scenarios:
  - engine: "ws"
    flow:
      - send: "hello"
      - think: 1
      - send: "world"
```

while i use  "wss://echo.websocket.org" for test, i got the right return
