### ISSUE TITLE
how to send multiple parameters in artilery's yaml script to socket.io

### ISSUE THREAD

**Issue by hkandukuri** [shoreditch-ops/artillery#424]
I have a socket.io function,

`socket.emit("newConnection", userHandle, groupId, boardId);`
How to establish a new connection using the above function from the YAML script. I tried the below approach.
```
scenarios:
  - name: "A chatty user"
    weight: 100
    engine: "socketio"
    flow:
      - emit:
          channel: "newConnection"
          data: '{ "userHandle": "abcd", "groupId": "1", "boardId": "1" }'
```
But this does not work. Tried few other ways, but none of them helped. 

Is Artillery supporting to send multiple parameters? If so how to call the above-stated function from the YAML script?
