### ISSUE TITLE
Ip Address in Config Target

### ISSUE THREAD

**Issue by bmeverett** [shoreditch-ops/artillery#428]
Are ip addresses supported in the target field? I'm trying to test a connection to a local server.  The output of the console keeps repeatedly showing NaN for the results. Is this supported or plans for this to be supported?

Here is my config file for reference: 

```
config:
  target: '192.168.0.113'
  phases:
    - duration: 60
      arrivalRate: 20
scenarios:
  - flow:
    - get:
        url: "/api/v2/report"
```
