### ISSUE TITLE
p95 and p99 are NaN most of the times

### ISSUE THREAD

**Issue by cskru** [shoreditch-ops/artillery#429]
```yaml
all scenarios completed
Complete report @ 2018-02-23T09:24:06.634Z
  Scenarios launched:  8
  Scenarios completed: 8
  Requests completed:  8
  RPS sent: 0.2
  Request latency:
    min: 7780.8
    max: 39701.4
    median: 23229.9
    p95: NaN
    p99: NaN
  Scenario duration:
    min: 7804.8
    max: 39703.9
    median: 23231.1
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 8 (100%)
  Codes:
    200: 8
```

In the above report you can see that all 8 requests are served.
Yet, p95 and p99 are NaN.
Isn't it a bug?
Or, do you suggest any tweaks here to make it work?
