### ISSUE TITLE
Concurrent users low than expected in the scenario

### ISSUE THREAD

**Issue by adil-haddaoui** [shoreditch-ops/artillery#434]
Hi,
My scenario is :
```
  phases:
    - duration: 300
      arrivalCount: 50
      arrivaleRate: 10
```
I'm trying to test with constant 50 users and I followed this solution #353 

But why in Concurrent users graph I see that the max count is 6  ( y_accessor ) ?

Any one could help ? is that a bug or does this concurrent users means something else ?

![screenshot-2018-3-1 artillery report](https://user-images.githubusercontent.com/5364177/36844589-4552a07a-1d4b-11e8-8a40-c10be3e7eb87.png)
