### ISSUE TITLE
Artillery gives ETIMEOUT and ESOCKETTIMEOUT, though the server runs perfectly. Also, there is a mismatch in number of scenarios launched and ETIMEOUTs received in the artillery output.

### ISSUE THREAD

**Issue by cskru** [shoreditch-ops/artillery#436]
**yml:**
```yml
config:
  payload:
    path: "file.csv"
    fields:
      - "name"
    order: "sequence"
  target: 'http://localhost:8000'
  phases:
    - duration: 1
      arrivalCount: 30
scenarios:
  - flow:
    - get:
        url: "/path/{{ name }}"

```
**Output:**
```
all scenarios completed
Complete report @ 2018-03-07T04:03:38.796Z
  Scenarios launched:  30
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: 0.24
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 30 (100%)
  Errors:
    ETIMEDOUT: 58
    ESOCKETTIMEDOUT: 4
```
Why are the numbers out of sync?
I have sent 30 requests. But ETIMEOUT is 58 and ESOCKETTIMEOUT is 4.
What do they mean?

Also, **I cannot see any anomaly in my server. It accepts 30 requests and runs perfectly.**
In between, artillery stops, giving this message.
Any help is much appreciated.
