### ISSUE TITLE
No nested json payload objects

### ISSUE THREAD

**Issue by aconfee** [shoreditch-ops/artillery#448]
Hello!

I've looked everywhere possible and tried everything I can think of, and can't find a way to add a nested object as a json payload.

scenarios:
&nbsp;&nbsp;flow:
&nbsp;&nbsp;&nbsp;&nbsp;post:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url: "/api/Offers"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;json: 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;newOffer: "{\"subscriptionId\": \"myid\"}"

(Hyphens removed because they caused markdown formatting errors)

The object I'm trying to send is 
`{ newOffer: { subscriptionId: "myid" } }` 

I've tried not using quotes, not breaking the quotes, and doing yaml format like so:
newOffer
  subscriptionId: "myid"

It doesn't seem like this is possible to accomplish... which I honestly can't believe since it's such a basic feature. Is this hidden in the documentation somewhere? If not, possibly change this ticket to reflect how to do this in the docs. At any rate, is this possible?

**Comment by hassy** [comment]
This should work:

```yaml
scenarios:
  - flow:
      post:
        url: "/api/Offers"
        json:
          newOffer:
            subscriptionId: myId
```

What your example is doing is setting the value of `newOffer` to a string, but you can just set the value of `json` to an arbitrary object which will be serialized and sent as JSON.

The docs can probably be updated to make this clearer!

**Comment by aconfee** [comment]
Thanks for your quick response, @hassy! Unfortunately, it looks like this still isn't working (I tried quotes around "myId" as well). When I debug the endpoint getting hit, subscriptionId is still coming in as null. To at least mostly rule out serialization issues, I made sure that I could get this same call to succeed in my Swagger spec, and it did. The literal JSON being sent is 
`{
  "subscriptionId": "myId"
}`

Any ideas what could be going wrong here, or what simple dummy tests I could try? Is there any other info I could give you to be more helpful? Thanks!

**Comment by hassy** [comment]
I can't reproduce the issue. The only thing I can think of is updating to the latest version of Artillery.

As you can see here the request body is as expected:

<img width="568" alt="artillery zsh 2018-03-31 23-58-45" src="https://user-images.githubusercontent.com/1490/38168272-888b1e38-353f-11e8-8176-7744393794b0.png">

The test script is:

```yaml
config:
  target: http://localhost:8111
  phases:
    - arrivalCount: 1
      duration: 1
scenarios:
  - flow:
      - post:
          url: "/"
          json:
            newOffer:
              subscriptionId: myId
```
