### ISSUE TITLE
docs: using path on socket.io

### ISSUE THREAD

**Issue by onedge-neptunez** [shoreditch-ops/artillery#452]
Hi, there.

I have used your awesome product for some tests.
But I found a wrong guide on your document - [socket.io reference](https://artillery.io/docs/socketio-reference/#path)

If someone want to use path of socket.io, they must describe like this.

**WRONG)**
```yml
config:
  target: "https://myapp.staging:3002/admin"
  socketio:
    query:
      path: "/mypath"
```
**RIGHT)**

```yml
config:
  target: "https://myapp.staging:3002/admin"
  socketio:
    path: "/mypath"
```

Please check this issue for other users.

Thank you for your product.
