### ISSUE TITLE
Unable to capture json value from response

### ISSUE THREAD

**Issue by tylerbhughes** [shoreditch-ops/artillery#455]
I'd like to start by saying that I tried to get help from the Gitter chat but it seems to be mostly quiet in there. In my project I've got a json response with a property that's nested a couple layers deep. It looks something like this:

```json
{
    "data": {
        "person": {
           "name": "John"
       }
    }
}
```

I'm using the capture below to try and get the name property from the response so I can add it to my url in the next request (via the variable). 

```json
"capture": [{
     "json": "$.data.person.name",
     "as": "name"
}],
```

However, anytime I hit that next request the name is empty even if I know it's got a valid response. What am I overlooking?

**Comment by tylerbhughes** [comment]
I'm on 1.6.0-15.

Yes, I see my logging statement, but the value is empty.

**Comment by tylerbhughes** [comment]
Sorry, didn't mean to close the issue.

**Comment by hassy** [comment]
Could you post the full request spec that the `capture` is part of? I can't reproduce the issue locally at the moment. Have you confirmed that the server definitely returns that payload?

**Comment by tylerbhughes** [comment]
> Could you post the full request spec that the capture is part of?

I can't post exactly what I'm doing since it's work related but here's what my spec looks like. All I changed was the url, and what json and the json. The structure of this spec is identical to my own.

```
"post": {
    "url": "/api/users/1",
    "headers": {
        "Content-Type": "application/json",
	"authorization": "{{ authorizationHeader }}"
    },
        "capture": [{
            "json": "$.data.person.name"
            "as": "name"
        }],
    "json": {
        "lastName": "Doe"
    }
}
```


> Have you confirmed that the server definitely returns that payload?

Yes, I can hit the endpoint with Postman using the same payload and I get the results I expect.

**Comment by hassy** [comment]
It does not look like the issue is with the capture mechanism:

```
curl -X POST -H "accept:application/json" -d '{}' http://demo2298800.mockable.io/test 

{
    "data": {
        "person": {
           "name": "John"
       }
    }
}
```

Then if I run the following Artillery script, it outputs "John" as expected:

```yaml
config:
  target: "http://demo2298800.mockable.io"
  phases:
    - duration: 1
      arrivalCount: 1
scenarios:
  - flow:
      - post:
          url: "/test"
          json: {}
          capture:
            - json: "$.data.person.name"
              as: name
      - log: "name is {{ name }}"
```

I would suggest making sure that `authorizationHeader` is being set correctly, and that the response is indeed what you expect (you can capture the entire response with just `$` and log that).
