### ISSUE TITLE
How does this work with a SPA?

### ISSUE THREAD

**Issue by fergardi** [shoreditch-ops/artillery#460]
Hello! Love this project.

I'm having issues to make it work with a SPA (Single Page Application). I have a project with VueJS (https://vuejs.org/), which has a router with one route `/example,` and this simple setup:

```
config:
  target: 'http://localhost:8088/#/'
  http:
    timeout: 30
    tls:
      rejectUnauthorized: false
    ws:
      rejectUnauthorized: false
    pool: 1
  phases:
    - duration: 3
      arrivalRate: 1
  defaults:
    headers:
      Authorization: 'Bearer fb8ea18e-38c9-459d-ba74-35c1c9ee5a40'
scenarios:
  - name: "test 1"
    flow:
    - log: New virtual user
      get:
        url: "/example"
```

But I allways get this output with all NaN results:

```
All virtual users finished
Summary report @ 18:15:45(+0200) 2018-05-07
  Scenarios launched:  3
  Scenarios completed: 3
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    test 1: 3 (100%)
```

I assume the NaN are appearing because it cannot reach my url and thereof no request is generated. What am I doing wrong?

Thanks in advance.

**Comment by hassy** [comment]
You just need a little fix in your YAML: `get` needs to be an element under `flow` rather than under `log`, so:

```yaml
scenarios:
  - name: "test 1"
    flow:
    - log: New virtual user
    - get:
        url: "/example"
```
