### ISSUE TITLE
WebSocket example

### ISSUE THREAD

**Issue by fergardi** [shoreditch-ops/artillery#461]
Hello again!

Now I'm trying to do a WebSocket load testing case scenario (using cometd over WS, https://cometd.org/), but I do not fully understand the documentation example.

How can I test a channel connection? What do I need to send using the `send` attribute? The name of the channel to connect to? The json to send to the backend in order to stablish a connection? How can I make a handshake? Using an external javascript?

Currently this is my example:

```
config:
  target: "wss://localhost:18443/api/cometd"
  phases:
    - duration: 20
      arrivalRate: 10
  ws:
    rejectUnauthorized: false
scenarios:
  - engine: "ws"
    flow:
      - send: "/room/channel/IDXXXXX"
      - think: 30
```

This is supposed to create 200 virtual users connecting to this channel and maintaining the connection opened for 30 seconds. This is my result:

```
All virtual users finished
Summary report @ 11:12:06(+0200) 2018-05-08
  Scenarios launched:  200
  Scenarios completed: 200
  Requests completed:  200
  RPS sent: 3.97
  Request latency:
    min: 0.3
    max: 2.9
    median: 0.4
    p95: 0.5
    p99: 1.1
  Scenario counts:
    0: 200 (100%)
  Codes:
    0: 200
```

Why am I receiveing the code 0? What this does mean? Is actually sending/receiveing data throught the channel? How can I test/debug/log this?

Thanks in advance.
