### ISSUE TITLE
new users load test not reflected on google analytics

### ISSUE THREAD

**Issue by matt212** [shoreditch-ops/artillery#462]
Hi, 
my yml file config is 

my Node version is v10.0.0
my artillery version is 1.6.0-15

```
config:
  target: 'http://[website name].com'
  phases:
    - duration: 60
      arrivalRate: 20
  defaults:
    
scenarios:
  - flow:
    - get:
        url: "/"
```

my query is what config in artillery  is required to reflect  the result in google analytics dashboard especially in real time tab in GA.
