### ISSUE TITLE
Cannot read property 'capture' of null

### ISSUE THREAD

**Issue by d1820** [shoreditch-ops/artillery#479]
Error everytime trying to run a post, and with no check or verify yaml options, or verbose output not sure how i would tell what the issue is if its even related to the yaml file at all.

Version: 1.6.0-18

YAML
```
config:
    target: 'https://test.net'
    http:
        tls:
            rejectUnauthorized: false
        pool: 10
    phases:
        - duration: 10
          arrivalRate: 1
scenarios:
    - flow:
      - log: 'New virtual user authorizing'
      - post:
        url: '/api-authorizations/authorize'
        headers:
            Content-Type: application/json
            Accept: application/json
            ClientId: 123
        json:
            Audience: 'http://abc.com'
            ClaimSets: [1]
            Claims: 
              - Type: 'domain'
                Value: 'test.comt'
                ValueType: 'string'
                Issuer: 'http://postman.abc.com'
              - Type: 'extension_UserId'
                Value: '1'
                ValueType: 'string'
                Issuer: 'http://postman.abc.com'
```

Command Ran
```
 artillery run test.yaml
C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\lib\commands\run.js:307
        (params.capture && params.capture.xpath) ||
               ^

TypeError: Cannot read property 'capture' of null
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\lib\commands\run.js:307:16
    at Array.forEach (native)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\lib\commands\run.js:304:19
    at Array.forEach (native)
    at checkIfXPathIsUsed (C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\lib\commands\run.js:303:20)
    at fn (C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:746:34)
    at C:\Users\Administrato\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:1213:16
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:166:37
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:706:43
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:167:37
```
