### ISSUE TITLE
multiple websockets flows

### ISSUE THREAD

**Issue by damianobarbati** [shoreditch-ops/artillery#485]
Is it possible to use scenarios with engine=ws? I know the error reported here is because of syntax (crappy yml, why not json?!) but before debugging yml I was wondering if "scenarios.name" could be used in combo with "scenarios.engine=ws" in order to simulate different random users doing actions on the socket.

```
config:
  target: "wss://localhost:3000"
  phases:
    - duration: 1
      arrivalRate: 1
  ws:
    rejectUnauthorized: false
scenarios:
  - engine: "ws"
  - name: 'damiano'
    flow:
    - send: '{"type":"setActive","value":true}'
    - think: 2.5
    - send: '{"type":"setActive","value":false}'
    - think: 2.5
    - send: '{"type":"setAvailable","value":true}'
    - think: 2.5
    - send: '{"type":"setAvailable","value":false}'
    - think: 2.5
    - send: '{"type":"setActive","value":true}'
    - think: 2.5
    - send: '{"type":"setActive","value":false}'
    - think: 2.5
  //here I'll put another user flow!
```

Yaml error:
```
/Users/damiano/Desktop/tav-server/node_modules/artillery/lib/commands/run.js:304
    scenario.flow.forEach(function(step) {
                  ^

TypeError: Cannot read property 'forEach' of undefined
```
