### ISSUE TITLE
Socket.io emit not working on latest version (1.6.0-20)

### ISSUE THREAD

**Issue by rafaponieman** [shoreditch-ops/artillery#495]
On this version (1.6.0-20), I'm getting the following error with a normal socket.io emit. Downgrading to 1.5.8-3, or removing the emit statement fixes the problem.

```
Started phase 0, duration: 60s @ 14:35:21(-0300) 2018-06-26
⠹ /usr/local/lib/node_modules/artillery/core/lib/engine_util.js:193
  if (o.constructor === Object) {
        ^

TypeError: Cannot read property 'constructor' of undefined
    at template (/usr/local/lib/node_modules/artillery/core/lib/engine_util.js:193:9)
    at preStep (/usr/local/lib/node_modules/artillery/core/lib/engine_socketio.js:234:34)
    at fn (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:1209:30
    at done (/usr/local/lib/node_modules/artillery/core/lib/engine_socketio.js:313:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/artillery/core/lib/engine_socketio.js:277:7)
```

Here's my yml file
``` yml
config:
  target: "http://localhost:4000"
  phases:
    - duration: 60
      arrivalRate: 1
  socketio:
    transports: ["websocket"]
    query:
      path: "/socket.io"
      cookieData: "xxxx"
scenarios:
  - engine: "socketio"
    flow:
      - emit:
          channel: "curso-24"
          data: [24, 1, "Rafa"]
      - think: 10
```
