### ISSUE TITLE
Extracting and Reusing parts of response - Does not seem to correctly for boolean values within json

### ISSUE THREAD

**Issue by sithara** [shoreditch-ops/artillery#497]
I'm trying to use the response received from `/orders/create` to be fed into `/orders/status`. But while printing the request , I can see that "{{placed}}" is being considered as an empty string and not as a boolean value.

Please find the code snippet below:

```
config:
  target: "http://127.0.0.1:8000"
   http:
    tls:
      rejectUnauthorized: false
    #timeout: 10
  phases:
    - duration: 1
      arrivalRate: 4
scenarios:
  - flow:
       - post:
          url: "/orders/create"
          capture:
            - json: $.data.orderId
              as: pid
            - json: $.data.orderPlaced
              as: placed
          -post:
             url: '/orders/status'
             json:
                placed: "{{placed}}"
```
 
Thanks much for the support
