### ISSUE TITLE
event emit again in socketio response body

### ISSUE THREAD

**Issue by FlyingFishBird** [shoreditch-ops/artillery#503]
### artillery version
1.6.0-22

### engine
socketio

### issue example
```yaml
      - emit:
          channel: 'echo'
          data: 'hello'
          response:
            channel: 'echoed'
            data: 'hello'
```

If you write 'response' param, the 'echo' event will sent again when 'echoed' event is received.
I fount this issue in server log.
And this issue is in function 'SocketIoEngine.prototype.step'
