### ISSUE TITLE
Support using environment variable in payload path

### ISSUE THREAD

**Issue by ryan-gustafson** [shoreditch-ops/artillery#505]
It would be nice to be able to select a different payload file by environment, say like:
```yaml
payload:
  path: "{{environment}}-scenarios.csv"
  fields:
    - "field1"
    ...
    ...
    - "field9000"
```

For two reasons:
1. Some data like login credentials changes between environments.
2. The fields are the same regardless of environment, so there is no point to redefine by putting the payload in each environment.

I had tried using `$environment`, `{{$environment}}`, `{{environment}}` and `{{ environment }}`.
