### ISSUE TITLE
Support for processor in WS engine

### ISSUE THREAD

**Issue by patilarpith** [shoreditch-ops/artillery#510]
Posted this on Gitter to no avail. 

I have a slightly complex message structure which I'm passing via a processor function but I see a crash at https://github.com/shoreditch-ops/artillery/blob/master/core/lib/engine_ws.js#L70
with message:
TypeError: Cannot read property 'toString' of undefined

So I was wondering if my configuration file was incorrect or support for processor in WS engine is not available yet

```yaml
config:
  target: "ws://localhost:8000/"
  phases:
    - duration: 5
      arrivalRate: 5
  ws:
    rejectUnauthorized: false
  processor: "./generator.js"
scenarios:
  - engine: "ws"
    flow:
      - function: "generateData"
      - send: "{{ message1 }}"
      - think: 2
      - send: "{{ message2 }}"
      - send: "{{ message3 }}"
      - think: 5
```
