### ISSUE TITLE
randomNumber not working in socketio query

### ISSUE THREAD

**Issue by sheepcloner** [shoreditch-ops/artillery#551]
I have spent about 3 hours trying to figure this out and now I am convinced there is a bug. This bug seems to have been reported to artillery before the merge with this repo. Somehow during the merge the issue cropped back up.

In short I am trying to user a random variable in the socketio `query`. I have tried `variables`, `functions` and finally the `randomString` and `randomNumber` built in functions. 

I am using artillery version `1.6.0-24`

Here is my current code:
```
config:
  target: "I intentionally removed the URL for this post"
  phases:
    - duration: 60
      arrivalRate: 5
  socketio:
    query:
      userId: 'user_{{$randomNumber(1,100)}}'
scenarios:
  - engine: "socketio"
    flow:
      - emit:
          channel: "nextRound"
          data: {}
      - think: 30
```

I get this error:

```
/usr/local/lib/node_modules/artillery/core/lib/engine_util.js:223
        if (funcName in context.funcs) {
                     ^

TypeError: Cannot use 'in' operator to search for '$randomNumber' in undefined
    at template (/usr/local/lib/node_modules/artillery/core/lib/engine_util.js:223:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/artillery/core/lib/engine_util.js:202:21)
    at walker (/usr/local/lib/node_modules/artillery/node_modules/traverse/index.js:190:22)
    at /usr/local/lib/node_modules/artillery/node_modules/traverse/index.js:208:29
    at Array.forEach (<anonymous>)
    at forEach (/usr/local/lib/node_modules/artillery/node_modules/traverse/index.js:298:31)
    at walker (/usr/local/lib/node_modules/artillery/node_modules/traverse/index.js:203:13)
    at /usr/local/lib/node_modules/artillery/node_modules/traverse/index.js:208:29
    at Array.forEach (<anonymous>)
    at forEach (/usr/local/lib/node_modules/artillery/node_modules/traverse/index.js:298:31)
```

Any help is most appreciated.
