### ISSUE TITLE
Cannot capture socket.io response

### ISSUE THREAD

**Issue by toxtox7** [shoreditch-ops/artillery#560]
>         - loop:
>          - emit:
>             channel: "test channel 1"
>            data: "12345"
>              response:
>                 channel: "system"
>                data: "12345"
>              function: "doSomething"

Artillery does compare the response but there doesn't seem a way to use it in a function. How is the data object accessible from either context, event or done?
The other alternative, using capture does not seem to work with socket.io. So how can I get the response into a Javascript function?

**Comment by toxtox7** [comment]
Thanks. It should not be too hard to do it. It seems that there is a response.data object that basically only seems to need to be added to the context as a var.

**Comment by gregormci** [comment]
has anyone been able to figure this out yet? i've tried but to no avail. Just need to use data from the response.

**Comment by gregormci** [comment]
```
     - emit:
        channel: "test channel 1"
       data: "12345"
         response:
            channel: "system"
            capture:
              - regexp: '[\s\S]+'
                as: "res"
  -  function: "doSomething"
```
`context.vars.res` now has the response from that socket.io response. however for me anyway not all the response messages were there... only seems to have the first message.
