### ISSUE TITLE
GZIP responses

### ISSUE THREAD

**Issue by Quilamir** [shoreditch-ops/artillery#574]
There is no way to tell artillery to use the ```gzip: true``` option in the request.

This causes the response to remain compressed and unreadable by artillery and impossible to build a flow test (cant get the values i need from the response in order to set it in the next request)

**Comment by Quilamir** [comment]
OK i figured it out

in the specific request you need to set gzip to be true for example:

```
scenarios:
  - flow:
    - post:
        gzip: true
        url: "someURL.com"
```
this is not mention anywhere in the documentation
